### ISSUE TITLE
ng-model set to object instead of value

### ISSUE THREAD

**Issue by asaveliev** [Siyfion/angular-typeahead#42]
The dropdown apparently expects data in [{value:"foo"}, ... ] format, if you pass array of strings it won't work (shows "undefined" as values in dropdown) . However, when value is populated from dropdown it sets ng-model to that {value:"foo"} object - not string. I have modified the updateScope method to set suggestion.value , but I am not sure what is the right fix.

**Comment by max-l** [comment]
I find that sometimes I want the object saved to the model, other times I want something computed from the datum. This pull request allows customizing what gets saved to the model : https://github.com/Siyfion/angular-typeahead/pull/62

**Comment by vhermecz** [comment]
#52 already resolved this by adding support for the suggestion-key="fieldname" tag to be specified on the  <input> node.
