### ISSUE TITLE
Two-Way Binding and Deleting The Field

### ISSUE THREAD

**Issue by rince1013** [Siyfion/angular-typeahead#44]
I'm having an issue where when I use the two-way binding feature by setting the model, and then deleting the entire field, the model isn't updating to reflect the data is deleted.

This can be reproduced on the demo
Steps:
http://plnkr.co/edit/cMvm7Z4REuIP69Uk4Tzz?p=preview
1. Press the 'Set value (two-way demo)' button
2. Verify that the model label is updated to 'Model: { "num": "seven" }'
3. Select the entire value 'seven' in the input box and delete
4. The model label is still 'Model: { "num": "seven" }'

Note. On step 3, if you delete 'seven', one character at a time, the model is updated

**Comment by phra** [comment]
is this bug been fixed?

**Comment by Siyfion** [comment]
@phra Nope, not as yet (#65), feel free to have a go if you like!

**Comment by hmil** [comment]
This bug seems to be gone in v1.0.0.
