### ISSUE TITLE
typeahead input with default data returns $dirty = true

### ISSUE THREAD

**Issue by Ir1sh** [Siyfion/angular-typeahead#48]
please see this plunkr http://plnkr.co/m73ZnijNfF2H6HsjbuCu

all inputs are in separate forms and the first two forms use angular-typeahead.  the second two do not.

you can see in the first input that $pristine = true and $dirty = false.  in the second where there is a default / existing value in the typeahead input the $pristine = false and $dirty = true.

You can see in the last two forms that the default angular behavior seems to be to load a form with default / existing values as $pristine = true and $dirty = false.

I am guessing that this falls under the angular-typeahead's umbrella as a wrapper for angular and not the actual typeahead project

Is this a known issue? intended behaviour? is there a workaround? might it be an easy fix for you guys?

**Comment by Flo-G** [comment]
I've run into a similar problem with other directives using ngModelCtrl.

Calling $setViewValue will set the form as dirty.
I think the one causing the issue is the one in the "initialize" function.

**Comment by darinda** [comment]
Hey,

i can confirm that the dirty state is called by [the $setViewValue call in the initialize function](https://github.com/Siyfion/angular-typeahead/blob/master/angular-typeahead.js#L109). Could anyone explain what it's there for anyway? Can't really see any reason to call $setViewValue here.

For now i just [created a fork](https://github.com/styleflashernewmedia/angular-typeahead) and commented out that line. Doesn't seem to have any negative side effects on my project.
