### ISSUE TITLE
Override value of typeahead input after typeahead:selected event

### ISSUE THREAD

**Issue by istian** [Siyfion/angular-typeahead#49]
Hi,

I'm able to override the value of the ngmodel when the typeahead:selected event fires but when the element lost focus ("blur") the original value is reverted although the ngModel still has the modified value. I guess this is  on typeahead.js behaviour not the directive. So from the documentation, I would like to try callling the typeahead("val", myval) but the problem is that the target element is not being returned by the directive. Isn't it supposed to return also the target elemen just like what typeahead does on "typeahead:selected" event?

Thanks

**Comment by ravikirankb** [comment]
Hi @istian i am having problems creating a directive for the typeahead:selected and typeahead:autocompleted events using the Siyfion/angular-typeahead. I am trying to use $scope.on to get the same but there are a list of typeahead controls so i am unable to determine which control the selected event is firing and i dont think there is an inbuilt directives to add in the HTML for selected and autocomplete events so i created a directive of my own but nothing seems to happen with that.

Please let me know how i can create a directive to add to each control to get the selected and autocompleted events.

**Comment by hmil** [comment]
Closing as this is > 1 year old. Please use `angular-typeahead` >=v1.0.0 from now on and open a new issue if your run into troubles again.
