### ISSUE TITLE
The Bare Bones usage example specifies that you use siyfion.sfTypeahead but I believe it should be siyfion.ngTypeahead 

### ISSUE THREAD

**Issue by samuelbirk** [Siyfion/angular-typeahead#57]

**Comment by samuelbirk** [comment]
This just seems to be true in the minified code

**Comment by Siyfion** [comment]
Nope, it definitely should be `siyfion.sfTypeahead`. Where did you find a reference to `siyfion.ngTypeahead`?

**Comment by samuelbirk** [comment]
It does seem to be resolved, but in a previous version of the minified code which I am going to paste below it had ngTypeahead

angular.module("siyfion.ngTypeahead",[]).directive("ngTypeahead",function(){return{restrict:"ACE",scope:{datasets:"=",ngModel:"="},link:function(e,n){n.typeahead(e.datasets),n.bind("typeahead:selected",function(n,t){e.$apply(function(){e.ngModel=t})}),n.bind("typeahead:autocompleted",function(n,t){e.$apply(function(){e.ngModel=t})})}}});
