### ISSUE TITLE
promise in controller

### ISSUE THREAD

**Issue by FangmingD** [Siyfion/angular-typeahead#58]
http://plnkr.co/edit/qCI09p2p8xXbrxD0F0e9?p=preview

what if I have a promise in my controller, similar to a timeout shown above, it might take some time to resolve before I have the data for typeahead.

however, it will not work anymore.

I tried to add a watch in the code, but it does not seem so nice...

**Comment by Siyfion** [comment]
Should be fixed in v0.2.2.
