### ISSUE TITLE
Possible to disable typeahead?

### ISSUE THREAD

**Issue by devourment77** [Siyfion/angular-typeahead#59]
Apologizes if I overlooked this, but is it possible to destroy or remove a typeahead after it has been initialized.  Example is if it has been used (hint or selected from drop down), to be able to turn it off.

Thanks,
Brandon

**Comment by hmil** [comment]
You should use ng-if and replace the element with a regular text input when you do not want the typeahead capabilities. The html is going to be a little different but with proper stylesheets it should not be visible to the end-user.
```js
<input ng-if="shouldEnableTypeahead" type="text" ng-model="myModel" sf-typeahead options="options" datasets="datasets" />
<input ng-if="!shouldEnableTypeahead" type="text" ng-model="myModel" />
```
I don't see the value of adding some extra logic to `angular-typeahead` given how easy it is to achieve with what's currently available.
