### ISSUE TITLE
Use ng-model-options' debounce

### ISSUE THREAD

**Issue by jonnyarnold** [Siyfion/angular-typeahead#60]
Currently angular-typeahead does not wait if an `ng-model-options="{ debounce: 5000 }"` is set on the element; it will search immediately.

Let me know if you need a Plunkr.

**Comment by hmil** [comment]
Is this still relevant? I am not familiar with `ng-model-options` and don't really know where the responsibility for implementing it lies. So if no one needs this feature I'm better off saving some time not investigating it.
Anyone needing this feature feel free to reply to this thread.
