### ISSUE TITLE
Cannot set property 'highlight' of undefined

### ISSUE THREAD

**Issue by ta-sh** [Siyfion/angular-typeahead#61]
When ng-controller is destroyed (or not initiated yet) appears an error:

-----   TypeError: Cannot set property 'highlight' of undefined  ------

It appears because you pass an [undefind] array to typeahead.js plugin when dataset is not defined.
The string: 
    (angular.isArray(scope.datasets) ? scope.datasets : [scope.datasets]) || [];
will never return the empty array, but it should for correct work of plugin

**Comment by hmil** [comment]
v1.0.0 should have taken care of this bug.
