### ISSUE TITLE
Firefox loose the value on focusout

### ISSUE THREAD

**Issue by Mogztter** [Siyfion/angular-typeahead#63]
Step to reproduce:
 1. Open the [live demo](http://plnkr.co/edit/cMvm7Z4REuIP69Uk4Tzz?p=preview) in Firefox
 1. Type seven
 1. Select the value in the combobox -> `Model: { "num": "seven" }`
 1. Click elsewhere on the page -> `Model: "seven"`

**Comment by CyborgMaster** [comment]
I'm having the same issue, have you found any work arounds yet?
