### ISSUE TITLE
Looking for a package maintainer...

### ISSUE THREAD

**Issue by Siyfion** [Siyfion/angular-typeahead#65]
Quite simply, I haven't had the time to keep this library up to date, or as robust as it should be, especially since I now am no longer using AngularJS in my day-to-day projects. Ideally, I'd like someone else to help maintain the project & I'll try to help as often as I can. So if you would be interested in taking a bit of a lead role on this, then please comment here...

**Comment by chevex** [comment]
What have you switched to in your day-to-day projects? Just curious.

**Comment by Siyfion** [comment]
@chevex I've moved almost entirely over to Meteor.

**Comment by hmil** [comment]
@Siyfion pm'd you on gitter

**Comment by hmil** [comment]
Looks like I am on board :sunglasses:
