### ISSUE TITLE
Typeahead 11.x support?

### ISSUE THREAD

**Issue by devourment77** [Siyfion/angular-typeahead#69]
Should we stick to using typeahead 10.x for angular-typeahead or is it safe to start using 11.x that was recently released?

**Comment by Siyfion** [comment]
@devourment77 that's a very good question, and I haven't had time to look at the release notes for `11.x` versions of Typeahead. Feel free to give it a try and let me know though! (I will have a look and update the package dependencies if it works okay)

**Comment by tomvo** [comment]
https://github.com/twitter/typeahead.js/blob/master/CHANGELOG.md#0110-april-25-2015

I'd like to have 0.11 support too but I guess it's necessary to do a bit of testing before jumping into 0.11.

**Comment by Siyfion** [comment]
@tomvo Ah bloody hell, that sounds ominous doesn't it... Well I guess there's only one way to find out, try it! :worried:

**Comment by tomvo** [comment]
@Siyfion Yeah, i'll see what I can do but if they write that there are core changes it sounds better to have a look at what changes they did and compare it with what the bindings of your library. That way you don't run into any edge-case situations.

**Comment by riddla** [comment]
I'm starting to try out typeahead `0.11` with the current angular-typeahead version (`0.2.3`) and gonna let you know how things are going.

**Comment by riddla** [comment]
So far I could directly re-use my existing configuration that I used with the typeahead `0.10` branch. No problems.

**Comment by Siyfion** [comment]
@riddla Awesome, good to know!

**Comment by rossmari** [comment]
Hi! we are all waiting for 11.1 version in dependencies! )

**Comment by Siyfion** [comment]
@rossmari Check that v0.2.4 is available and solves this dependency.

**Comment by Siyfion** [comment]
Closing as I haven't heard otherwise.
