### ISSUE TITLE
Firefox focus bugfix breaks update in Chrome

### ISSUE THREAD

**Issue by vhermecz** [Siyfion/angular-typeahead#71]
The patch from #67 by CyborgMaster blocks some model updates in Chrome (Version 43.0.2357.130 (64-bit))
Example: I'm clicking to one of the suggestions in the dropdown
Expected outcome: Model to be updated based on the selected suggestion
Current behaviour: The change to the value will be reverted by this firefox fix line when called from NgModelController.$$parseAndValidate, so writeToModelIfNeeded at the end will not do anything, thinking the value stayed the same...

(If the solution is to only run the line for FFox, https://github.com/srfrnk/ng-device-detector might be useful here)

**Comment by CyborgMaster** [comment]
Interesting. I just double checked the fix in chrome and everything is working fine for me.  Clicking on a suggestion successfully updates the model for me.  This might  deserve further investigation.
