### ISSUE TITLE
Firefox focus fix causes form to be invalid

### ISSUE THREAD

**Issue by peterox** [Siyfion/angular-typeahead#72]
The fix made for the firefox workaround causes the field to be invalid as it can return 'undefined'.

When the page is initially loading the parse function is executed and the check 
```
if (fromView === element.typeahead('val')) return ngModel.$modelValue;
```
evaluates true and therefore returns $modelValue. The problem is that $modelValue can be undefined and returning undefined from a $parser signifies that the field is invalid.

**Comment by xiankai** [comment]
This fix also prevents me from using flat arrays for datasets, because the returned value is always the same as the displayed value

**Comment by phra** [comment]
"This fix also prevents me from using flat arrays for datasets, because the returned value is always the same as the displayed value"
same problem here: [#79](https://github.com/Siyfion/angular-typeahead/issues/79).

please remove that line or i'll need to fork your repo and remove that commit.

**Comment by phra** [comment]
you can close also this ticket.
cheers.
