### ISSUE TITLE
ReferenceError: Bloodhound is not defined

### ISSUE THREAD

**Issue by zeeshanjan82** [Siyfion/angular-typeahead#73]
When I try to use this module, I get the error
````js
ReferenceError: Bloodhound is not defined
````
I have referenced the version 0.11.1 from npm https://www.npmjs.com/package/typeahead.js

**Comment by zeeshanjan82** [comment]
I only use typeahead.bundle.js file

**Comment by Siyfion** [comment]
I would have thought that it's pretty self-explanatory, you don't have the bloodhound library installed. It is listed on the main page as a package dependency.
