### ISSUE TITLE
Add support for custom template

### ISSUE THREAD

**Issue by claycephas** [Siyfion/angular-typeahead#78]
Please add support for custom templates.

https://twitter.github.io/typeahead.js/examples/

**Comment by claycephas** [comment]
Similar to the way Angular UI accomplishes this:
https://angular-ui.github.io/bootstrap/

**Comment by brunowego** [comment]
Yes, this feature can help a lot of devs.

**Comment by brunowego** [comment]
Works here:

```js
  vm.itemsDataset = {
    displayKey: 'title',
    source: items.ttAdapter(),
    templates: {
      empty: [
        '<div class="tt-suggestion tt-empty-message">',
        'No results were found ...',
        '</div>'
      ].join('\n'),
    }
  };
```

**Comment by Siyfion** [comment]
I was going to say, this should just work, if it's supported in Typeahead.js! Any more comments to say otherwise?

**Comment by claycephas** [comment]
Thanks for the example @brunowego. Will it also be possible to specify a template for each item in the list and perform binding (e.g. {{myModel.myProperty}})? If so, could you provide an example?

**Comment by brunowego** [comment]
@claycephas try use [something like this](https://gist.githubusercontent.com/jharding/9458780/raw/69572177436dd77df5cf3a8450963935f84c1b58/custom-templates.js).

**Comment by nishadk123** [comment]
@brunowego @claycephas could you guys find a way to bind angular elements to the templates ?
```javascript
   notFound : function(e) {
            return $compile('<div ng-click="alert(123)">Not found</div>')($scope);
   }
```
It does not work.. Is there any way out of this? I want to call a angular controller function on click of the not found result.

**Comment by claycephas** [comment]
@nishadk123 Have not had a chance to try it yet

**Comment by craHUNzyTER** [comment]
@nishadk123 did you find solution to call angular controller on ng-click from notFound template? 


Or could @hmil inform when this issue would be closed, if there are «needs testing» and «needs doc» tags added?

**Comment by hmil** [comment]
This issue will be closed once this feature is tested and documented. I'm assuming it should "just work" as this module forwards the "options" parameter unmodified.

Actually, I just tried @brunowego's solution and it worked. I updated the [plunkr](http://plnkr.co/edit/k2JWu6tZMXwkB8Oi9CSv?p=preview) and since this escapes the control of `angular-typeahead`, I don't think it needs testing after all.
