### ISSUE TITLE
'Fix firefox focus bug' introduced another bug.

### ISSUE THREAD

**Issue by phra** [Siyfion/angular-typeahead#79]
the commit 61b5a173c5e0ba5389200e680c4e994dcaff011d introduced a very nasty bug that got me six hours to find.

in this plunker http://plnkr.co/edit/cMvm7Z4REuIP69Uk4Tzz just make this change 
```javascript
        ngModel.$parsers.push(function (fromView) {
          // Assuming that all objects are datums
          // See typeahead basics: https://gist.github.com/jharding/9458744#file-the-basics-js-L15



//ADD THIS LINE
          if (fromView === element.typeahead('val')) return ngModel.$modelValue; //FF FOCUS FIX ???



          var isDatum = angular.isObject(fromView);
          if (options.editable === false) {
            ngModel.$setValidity('typeahead', isDatum);
            return isDatum ? fromView : undefined;
          }

          return fromView;
        });
```
after making this change (FF FOCUS FIX) the plunker starts to ignore TAB and CLICK events. please remove 61b5a173c5e0ba5389200e680c4e994dcaff011d or i'll need to fork your repo.

**Comment by Siyfion** [comment]
@phra It doesn't for me...?

**Comment by phra** [comment]
hi,

i've noticed that you have to make another change in the plunker to reproduce the bug.

declare variable numbers like this:

```javascript
  // instantiate the bloodhound suggestion engine
  var numbers = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    local: ['one', 'two']
  });
```

now the autocomplete ignores click and tab events.

**Comment by phra** [comment]
any feedback please?

**Comment by phra** [comment]
@CyborgMaster can you provide some feedback of your fix and how to make it working with plain arrays? see also duplicate ticket #72

**Comment by phra** [comment]
pull requested merged. closing ticket.
