### ISSUE TITLE
With 0.3.0, when using ng-model, the value is not changed after autocomplete

### ISSUE THREAD

**Issue by l2fprod** [Siyfion/angular-typeahead#81]
Hi,

The issue can be reproduced with the LIVE DEMO listed in https://github.com/Siyfion/angular-typeahead:
http://plnkr.co/edit/cMvm7Z4REuIP69Uk4Tzz?p=preview

* Type "s" in the model textfield
* Notice the model value changes to "s"
* In the typeahead dropdown, select "seven" and hit enter.
* The model value does not change
* -> it should have changed to "{"num": "seven"}

0.2.4 does not have the issue. It seems to come from this change: https://github.com/Siyfion/angular-typeahead/commit/5a82689175e49a01e3372c1bfed2c2fb229b8481
where getAllElements do not return any of the "typeahead:" event types.

regards,
-fred

**Comment by reneolivo** [comment]
I'm having the same issue! 

I also left a comment about a rogue `>`

**Comment by piyushbeli** [comment]
I too have the same issue. Thanks I saw this post otherwise I was thinking that this is something from angular.

**Comment by Siyfion** [comment]
There's a fundamental issue with #76 that's causing this... It will need investigating, or reverting.

**Comment by Siyfion** [comment]
I've reverted the event binding code for the time being.

**Comment by l2fprod** [comment]
updated. tested. works fine, thanks!
