### ISSUE TITLE
Correct typeahead version?

### ISSUE THREAD

**Issue by amilajack** [Siyfion/angular-typeahead#83]
Which version of typeahead should be used? The bower.json and the docs are conflicting

<img width="231" alt="screen shot 2015-12-25 at 12 43 33 pm" src="https://cloud.githubusercontent.com/assets/6374832/12004328/483d207c-ab05-11e5-8014-72696cf9bea5.png">
<img width="205" alt="screen shot 2015-12-25 at 12 43 40 pm" src="https://cloud.githubusercontent.com/assets/6374832/12004327/483ce29c-ab05-11e5-9e20-e39ef0a4ab1c.png">

**Comment by amilajack** [comment]
After messing around a bit, I can confirm that the 0.11.* version does not work with the current version of typeahead.

**Comment by hmil** [comment]
Now officially supporting `typeahead.js` v0.11.x
