### ISSUE TITLE
typeahead:closed to typeahead:close

### ISSUE THREAD

**Issue by cafesanu** [Siyfion/angular-typeahead#85]
Twitter typeahead changed `typeahead:closed` to `typeahead:close`, So the binding to `typeahead:closed` in here (https://github.com/Siyfion/angular-typeahead/blob/master/angular-typeahead.js#L150) is not working.

See this:
https://github.com/twitter/typeahead.js/blob/588440f66559714280628a4f9799f0c4eb880a4a/src/typeahead/typeahead.js#L333

Thanks!

**Comment by hmil** [comment]
Done in v1.0.0
