### ISSUE TITLE
Get "type" on multiple dataset

### ISSUE THREAD

**Issue by fzanollo** [Siyfion/angular-typeahead#88]
Hi, I have a search bar with multiple datasets and want to be able to know where the chosen suggestion came from.

Let's say I have:
```js
vm.sets= [
      {
        name: 'groupA',
        source: vm.groupA.ttAdapter(),
        templates: {
          header: '<h3 class="league-name">groupA</h3>'
        },
        displayKey: 'full_name'
      },
      {
        name: 'groupB',
        source: vm.groupB.ttAdapter(),
        templates: {
          header: '<h3 class="league-name">groupB</h3>'
        },
        displayKey: 'otherthing'
      }
    ];
```

Is there anyway to do that without manually adding the type to the object? Like an attribute of the selected element to know where it came from?

On master/angular-typeahead.js I found this function:
```js
function updateScope (object, suggestion, dataset) {
          scope.$apply(function () {
            var newViewValue = (angular.isDefined(scope.suggestionKey)) ?
                suggestion[scope.suggestionKey] : suggestion;
            ngModel.$setViewValue(newViewValue);
          });
 }
```

What does dataset contains? Why isn't it being used?

Thanks!

_**edit hmil:** please [format your code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) using triple quotes_

**Comment by hmil** [comment]
`angular-typeahead` itself doesn't know where the suggestion came from so this problem is not relevant to this module. All it provides is a raw integration of `typeahead.js` in angular. You should search if you can find a solution in [typeahead.js](https://github.com/twitter/typeahead.js).
